# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: lib/proto/open_project.proto for package ''

require "grpc"
require_relative "open_project_pb"

module Proto
  module OpService
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'OpService'

      rpc :SendMessage, ::MessageRequest, ::Result
      rpc :GetTemplates, ::Google::Protobuf::Empty, ::GetTemplateResp
      rpc :GetUserInfoByCode, ::GetUserInfoByCodeReq, ::RespUser
      rpc :SendWcWorkerMessage, ::WorkerMessageReq, ::Result
      rpc :SendImage, ::SendImageReq, ::Result
      rpc :GetPdf, ::GetPdfReq, ::GetPdfResp
      rpc :ShowEstimateButton, ::PlmProjectReq, ::ShowEstimateButtonResp
      # 待更新里程碑的项目 https://plm.thape.com.cn/projects/plmwenti/work_packages/391927/activity
      rpc :GetUpdateMilestoneProject, ::GetUpdateMilestoneProjectReq, ::GetUpdateMilestoneProjectResp
      # 待归档的项目列表 https://plm.thape.com.cn/projects/plmwenti/work_packages/391927/activity
      rpc :GetArchiveProjects, ::GetArchiveProjectsReq, ::GetArchiveProjectsResp
      # 预算超支的项目 https://plm.thape.com.cn/projects/plmwenti/work_packages/391927/activity
      rpc :GetBudgetOverrunProjects, ::GetBudgetOverrunProjectsReq, ::GetBudgetOverrunProjectsResp
      # 老系统创建工时数据同步
      rpc :SyncTimeEntries, ::SyncTimeEntriesReq, ::SyncTimeEntriesResp
      def self.current_client
        @@current_client ||= ::Gruf::Client.new(service: Proto::OpService)
      end
    end

    Stub = Service.rpc_stub_class
  end
end