# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: lib/proto/open_project.proto for package ''

require "grpc"
require_relative "open_project_pb"

module Proto
  module OpService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "OpService"

      rpc :SendMessage, ::MessageRequest, ::Result
      rpc :GetTemplates, ::Google::Protobuf::Empty, ::GetTemplateResp
      rpc :GetUserInfoByCode, ::GetUserInfoByCodeReq, ::RespUser
      rpc :SendWcWorkerMessage, ::WorkerMessageReq, ::Result
      rpc :GetPdf, ::GetPdfReq, ::GetPdfResp
      rpc :ShowEstimateButton, ::PlmProjectReq, ::ShowEstimateButtonResp

      def self.current_client
        @@current_client ||= ::Gruf::Client.new(service: Proto::OpService)
      end
    end

    Stub = Service.rpc_stub_class
  end
end